import Head from "next/head";
import Image from "next/image";
import HeroSection from "../components/indexPage/HeroSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <HeroSection />
      </main>
    </div>
  );
}
